[azure]
api_key = "df4bcebf8eb843e8bc0dca3d3dd88470"
endpoint = "https://zh-ais-hgpt-lab-weu-2.cognitiveservices.azure.com/" 
agent_id = "asst_E5nFroutEcRYyKkXsLkMwPvJ"
subscription_id="1a5dacdd-9142-41d9-b223-d6c3b6a5ab74"
resource_group_name="zh-rg-hgpt-lab-weu-1"
project_name="aip-gm-playground-swc-1"

AZURE_AI_AGENT_PROJECT_CONNECTION_STRING = "swedencentral.api.azureml.ms;1a5dacdd-9142-41d9-b223-d6c3b6a5ab74;zh-rg-hgpt-lab-weu-1;aip-gm-playground-swc-1"
AZURE_AI_AGENT_MODEL_DEPLOYMENT_NAME = "llm-GPT4o-100k-hagergptlab-medium-swc-1"
